### ISSUE TITLE
NR6Pack is not working with VS2015 CTP

### ISSUE THREAD

**Issue by DavidKarlas** [icsharpcode/NRefactory#456]
Two days ago VS2015 CTP was released and also new NuGet package beta2.
This are errors I got on running QuickFix in ActivityLog.xml:
https://gist.github.com/DavidKarlas/8f3ede27c30a16d8bee0

**Comment by Rpinski** [comment]
Should work now after c2fa14eafdc0f542f436b95467511b4d6f2bb917 and 51647cd475ae9703ab1562e957f5dac15e7d7462.
