### ISSUE TITLE
Getting MethodInfo from CSharpInvocationResolveResult

### ISSUE THREAD

**Issue by NinjaCross** [icsharpcode/NRefactory#465]
First of all, my best compliments for this great piece of art !
I have a question: given a CSharpInvocationResolveResult how can I get the real MethodInfo ?

**Comment by mkrueger** [comment]
You mean a .NET reflection MethodInfo ? 
There isn't a built in way of doing that since NR isn't about reflection - it's about NR. :)

You would need to load the assembly in reflection and search the type name and the matching method.

**Comment by NinjaCross** [comment]
Thankyou for your answer, but sorry, I don't get it....

I'm doing semantic analisys using the Type System, and to build the Type System you have to provide NR the dependent assemblies (as seen in http://www.codeproject.com/Articles/408663/Using-NRefactory-for-analyzing-Csharp-code).
So at some point NR needs them to make a reflection analisys on dependent types.

I've done it, and now I have a fully built Type System tree inside a ICompilation instance, which I used to initialize a new CSharpAstResolver.

The CSharpAstResolver can resolve the IMethod item given an AST node of a function call.
All I want is to get the MethodInfo instead of the IMethod (or DefaultResolvedMethod in my specific case).
Since I already had to load the dependent assemblies so ICompilation could use them, I assume that ICompilation would retain a sort of mapping between the Type System entities and the reflecion entities that it creates/wraps.

Here is mi code to initialize the CSharpAstResolver.
As you can see, the assemblies must be loaded and provided to CSharpProjectContent, so it can generate a ICompilation.

```csharp
    public void ResolveTypeSystem(Assembly[] assemblies)
    {
      if (SyntaxTree == null)
        throw new LanguageProcessorException("Cannot resolve the type system. No syntax tree loaded");

      SyntaxTree.FileName = Path.Combine((new FileInfo(GetType().Assembly.Location)).Directory.FullName, Guid.NewGuid() + ".cs");
      Lazy<IList<IUnresolvedAssembly>> builtInLibs = new Lazy<IList<IUnresolvedAssembly>>(
        delegate
        {
          if (assemblies == null)
          {
            assemblies = LanguageProcessorUtils.GetTypeSystemAssemblies();
          }

          IUnresolvedAssembly[] projectContents = new IUnresolvedAssembly[assemblies.Length];
          Stopwatch total = Stopwatch.StartNew();
          Parallel.For(
            0, assemblies.Length,
            delegate(int i)
            {
              Stopwatch w = Stopwatch.StartNew();
              CecilLoader loader = new CecilLoader();
              projectContents[i] = loader.LoadAssemblyFile(assemblies[i].Location);
              Debug.WriteLine(Path.GetFileName(assemblies[i].Location) + ": " + w.Elapsed);
            });
          Debug.WriteLine("Total: " + total.Elapsed);
          return projectContents;
        });

      AddOrUpdateFiles = new CSharpProjectContent();
      UnresolvedFile = SyntaxTree.ToTypeSystem();
      AddOrUpdateFiles = AddOrUpdateFiles.AddOrUpdateFiles(UnresolvedFile);
      AddOrUpdateFiles = AddOrUpdateFiles.AddAssemblyReferences(builtInLibs.Value);

      Compilation = AddOrUpdateFiles.CreateCompilation();

      Resolver = new CSharpAstResolver(Compilation, SyntaxTree, UnresolvedFile);
    }

```

**Comment by mkrueger** [comment]
No reflection involved here. Types are loaded either via Cecil or IKVM.
In the code above all what is used from reflection is the Location of the assembly. Cecil then loads the assemblies from disk again.

(The CecilLoader contains mappings to the cecil objects but I don't think that this is what you want).

We don't have a reflection -> assembly wrapper. (Wouldn't make sense in our use cases)

Why do you need the MethodInfo ? (The only thing I could imagine is invoking the method)

**Comment by NinjaCross** [comment]
Thankyou for the clarifications.
I need the MethodInfo because I must provide the user for some code-time checks based on information that I get from the attributes that decorate the method.
Do you have any idea how I could solve this problem ?

**Comment by mkrueger** [comment]
Just look in method.Attributes. 

NRefactory can give you any info you can get via reflection.
