### ISSUE TITLE
Code actions on unknown method are not useful

### ISSUE THREAD

**Issue by aeschli** [icsharpcode/NRefactory#470]
'roslyn' branch:
For the following code, get code actions on the reference to 'GetByEmailAsync' in Foo. The method exists, but needs arguments.
```cs
public class EmployeeRepository
{
  Task<Employee> GetByEmailAsync(string email, PictureType pictureType) { return null; }
}

public class Foo {
  public async Task<Employee> GetLoggedEmployeeInfo(EmployeeRepository rep)
  {
    return await rep.GetByEmailAsync();
   }
}
```
The proposals contain 'Create field', 'Create property' and 'Create local variable'
- 'Create field', 'Create property' and 'Create local variable' should not show given that 'GetByEmailAsync' is used with ().
- 'Create local variable' should be filtered given that GetByEmailAsync is a qualified access.
- It would be nice if there were a proposals that adds arguments or a proposal that modifies the method signature in EmployeeRepository.

**Comment by mkrueger** [comment]
The create actions were not really done well because roslyn already contains them. These actions got removed.
