### ISSUE TITLE
Mono.CSharp cannot be used with NRefactory

### ISSUE THREAD

**Issue by abock** [icsharpcode/NRefactory#475]
I have two large projects that use NRefactory and Mono.CSharp independently of each other for unrelated things. Because NRefactory bundles its own copy of Mono.CSharp, it conflicts with any other version (e.g. the assembly shipped with Mono).

NRefactory should change the namespace for its bundled Mono.CSharp and/or make it internal so projects can reference both NRefactory and another version of Mono.CSharp.

Currently I am having to bundle and build my own Mono.CSharp with a script that changes its namespace to avoid these conflicts.

**Comment by mkrueger** [comment]
fixed.
