### ISSUE TITLE
new code fix suggestion: Fluent interfaces

### ISSUE THREAD

**Issue by Kavignon** [icsharpcode/NRefactory#477]
I was thinking that we could create an analyzer that would look InvocationExpressionSyntax and make sure that when fluent calls are made, it's aligned properly.
When it's not done properly, we would fire a warning to the user.
Having this analyzer, it would be easy to write a code fix would align the code with the proper tabs.

This could be interesting as it would make code look cleaner and would improve readability of the source file

**Comment by mkrueger** [comment]
No - that's in the scope of a code formatter.

**Comment by Kavignon** [comment]
Should open a new issue an declare my idea in the scope of a code formatter
or this was simply not a good idea for NRefactory at the moment ?

On Friday, April 10, 2015, Mike Krüger <notifications@github.com> wrote:

> Closed #477 <https://github.com/icsharpcode/NRefactory/issues/477>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/icsharpcode/NRefactory/issues/477#event-278648071>.
>


-- 
Kevin Avignon
Étudiant en génie des technologies de l'information (ETS)

**Comment by mkrueger** [comment]
I think the code formatter should align them properly - however how that's aligned should be a formatting policy.

**Comment by Kavignon** [comment]
I'll open an issue stating we should create a code formatter to correctly align C#/VB within a source file

**Comment by Kavignon** [comment]
Is that okay @mkrueger ?

**Comment by mkrueger** [comment]
What's wrong with the roslyn formatter ? The code formatter is part of roslyn - you should open an issue to that project.

**Comment by Kavignon** [comment]
Actually nothing.  I thought we could just format code within a source
file.
I'll have to check out the code formatter from Roslyn as  ai've never used
it!
I understand now that it was a bad idea

On Sunday, April 12, 2015, Mike Krüger <notifications@github.com> wrote:

> What's wrong with the roslyn formatter ? The code formatter is part of
> roslyn - you should open an issue to that project.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/icsharpcode/NRefactory/issues/477#issuecomment-92022108>
> .
>


-- 
Kevin Avignon
Étudiant en génie des technologies de l'information (ETS)

**Comment by Kavignon** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Kevin

Confirm that you know Kevin: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=qkYDuhZe&invitationId=6208290943469182977&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eivzc5evk%7Ejq








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ivzc5evk-jq&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQEsQLlBl_a6zQAAAVihH1XHhOzNqsuOZ-m-QXmL7Vse-5lhdHGx_aVKv3OZGrDhLM0uxL9G52DpnhoD6Pqdozh54c013dRmkfbHPpbG-25CuTZ0LYjIooiKXhpqI8DYnAjU_kRknj_8iI8z6r9cXumrC214yTZ6bCId7B63aj7bSfMjRJOzFSySGu8SXy5iIDYbfWY4i5yICrZZ_uB4O51wPA&eid=0-ivzc5evk-jq


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ivzc5evk-jq&a=customerServiceUrl&ek=invite_guest

© 2016 LinkedIn Corporation, 1000 West Maude Avenue, Sunnyvale, CA 94085. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by Kavignon** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Kevin

Confirm that you know Kevin: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=i6c0c5yg&invitationId=6208290922371829760&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eivzc63la%7Eex








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ivzc63la-ex&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHon6FTMshG4QAAAVihH84egBNKfOcZyonk1kZkUP_pC6ZBGyBKhKgWbIopDRuV38ahsUpqs6nzbXHfJm_ybrZzY79ZjJewUGp2qGLO3Qv23i-KPYElVN41KL8CSIZKkG_Tym1hgfXb-cqErjEKgucHIM7fpE9OacI5yFyMw17tvNJo3vFDxMkh-P9Gx1rhvoxdYUEe24MmDXHbbkKDQ585-A&eid=0-ivzc63la-ex


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ivzc63la-ex&a=customerServiceUrl&ek=invite_guest

© 2016 LinkedIn Corporation, 1000 West Maude Avenue, Sunnyvale, CA 94085. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by Kavignon** [comment]
Kevin Avignon would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=i6c0c5yg&invitationId=6208290922371829760&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-a1n01w%7Eiw6mrc9d%7Epo

View Kevin Avignon&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=i6c0c5yg&invitationId=6208290922371829760&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-a1n01w%7Eiw6mrc9d%7Epo





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=a1n01w-iw6mrc9d-po&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=a1n01w-iw6mrc9d-po&loid=AQE5efFFyhlhSQAAAVi8MfKSqo44Xves38blm2PbnSW9yUCDQ-QAaQo7_EW3w7fggLLPHTiwzwwFriEsi8EmnCinlbVAd9CiQcQWN6DFF-MGQHrmxM1ibhBueQEPWxUSxAY5zjQ3YsYVaeZR7VTROOW2IK8uxDaT6FF1l02aspBIbcsWJGlru5_9umJoMGIU6t3jfys7uh8u_4u3_th8EiGH1RYitQ

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=a1n01w-iw6mrc9d-po&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by Kavignon** [comment]
Kevin Avignon would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=qkYDuhZe&invitationId=6208290943469182977&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-%7Eylw6n4%7Eiw6mrib2%7Eix

View Kevin Avignon&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=qkYDuhZe&invitationId=6208290943469182977&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-%7Eylw6n4%7Eiw6mrib2%7Eix





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-ylw6n4-iw6mrib2-ix&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=-ylw6n4-iw6mrib2-ix&loid=AQEooJWBGRwIQwAAAVi8MiuT0At8OjN6WKnUchki46ZqpXXSndTWbeBgAtBnLK-U1oLEDmmLRDbffkFscubfTdpD7Xt54WGuCrfB-aB2hmPvyjXZ310E97osnh7FAkGjnkcn-_BHgq2hoXba_AEsVK0boDMWll3iiwrmvEToXzZFqDIl82ljaWZSqfxjNwWamaJrn-5PzFuyt_Syi955HAQ4K1uHfg

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-ylw6n4-iw6mrib2-ix&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
