### ISSUE TITLE
Warning reported for empty catch with a filter.

### ISSUE THREAD

**Issue by YevgenijZ** [icsharpcode/NRefactory#484]
![emptycatchwithfilter](https://cloud.githubusercontent.com/assets/8945897/7879655/029070a6-05fb-11e5-8c97-a7fa93b3d8c1.png)

Warning "Empty general catch clause suppresses any error" is reported for empty catch block with a filter like { .. } catch when (..) {}.

The presence of filter makes this code intentional and not so unconditional.

**Comment by Rpinski** [comment]
Fixed with ba7c33bf666b249ed87f21bc73009a36e3537f7f.
