### ISSUE TITLE
ReplaceEmptyStringAction contains a critical bug

### ISSUE THREAD

**Issue by jernejk** [icsharpcode/NRefactory#495]
Hi,
I noticed that refactoring code bellow crashes Visual Studio while using NR6Pack library:
```csharp
Console.WriteLine("");
```

Most likely cause of this bug is trying to replace node received from context.GetNode<PrimitiveExpression>() which is probably returning ArgumentSyntax instead of StringLiteralSyntax. I'm doing a demo for Roslyn and I had this issue and I solved it by getting most inner node with same location:
```csharp
SyntaxNode node = root.FindNode(diagnostic.Location.SourceSpan, getInnermostNodeForTie: true);
```

I tried to fix this but I wasn't able to compile Test project and I'm familiar with framework used in here.
This is my naive solution because I didn't found "getInnermostNodeForTie" equivalent functionality:
```csharp
		static PrimitiveExpression GetEmptyString (RefactoringContext context)
		{
			var node = context.GetNode<PrimitiveExpression> ();
			if (node == null || !(node.Value is string) || node.Value.ToString () != "")
				return null;

            if (node.FirstChild.StartLocation.Column == node.StartLocation.Column)
            {
                var newNode = node.GetNextNode() as PrimitiveExpression;

                if (newNode is PrimitiveExpression)
                {
                    node = newNode as PrimitiveExpression;
                }
            }

            return  node;
		} 
```

**Comment by Rpinski** [comment]
Hi Jernej,

thanks for sharing this issue. One question: Which NR6Pack version did you test it with?

**Comment by jernejk** [comment]
It was from Visual Studio extension gallery for VS 2015 version 0.10.0.0.
I noticed today version 1.0 was pushed and it works. :)

Thanks!
