### ISSUE TITLE
CSharpOutputVisitor methods should be virtual

### ISSUE THREAD

**Issue by abock** [icsharpcode/NRefactory#499]
It would be very useful to have `CSharpOutputVisitor` methods as `virtual`. Currently the class implements `IAstVisitor` without making its implementation `virtual`, which means it is useless to subclass.

I have enough scenarios where I _mostly_ want the base visitor to generate C# code for me, in accordance with the provided `CSharpFormattingOptions` but in some cases need to customize visitation when writing code.

For example, I intentionally insert `TextNode` nodes in an AST for annotation purposes with the _intention of causing invalid C#/compilation failure_ so that generated code forces an audit in some cases.

**Comment by abock** [comment]
To clarify, this also means making most of the private members (such as `StartNode`, `Semicolon`, etc, even the `containerStack` `protected virtual`).

**Comment by mkrueger** [comment]
Fixed - let us know if anything is missing.
