### ISSUE TITLE
Error while transforming syntax tree to C# code

### ISSUE THREAD

**Issue by tlawrenz** [icsharpcode/NRefactory#500]
When parsing a (old) Web-Service with  "System.Xml.Serialization.XmlElementAttribute"
Example:
[return: System.Xml.Serialization.XmlElementAttribute ("bla", Namespace = "http://blub", IsNullable = true)]
public response getResponse([System.Xml.Serialization.XmlElementAttribute (Namespace = "http://blub", IsNullable = true)  ...

SyntaxTree.ToString() results in 

[@return: System.Xml.Serialization.XmlElementAttribute ("bla", Namespace = "http://blub", IsNullable = true)]
public response getResponse([System.Xml.Serialization.XmlElementAttribute (Namespace = "http://blub", IsNullable = true)  ...

the "@" before "return" results to wrong results on web service call (even though the compiler has no problem with that)

**Comment by dgrunwald** [comment]
This is already fixed on master. (part of commit 530d5b583fc378f98dd27e42067bfdef77b350da)
