### ISSUE TITLE
CodeConverter service not available

### ISSUE THREAD

**Issue by APopatanasov** [icsharpcode/NRefactory#524]
My application is using the codeconverter service. However, recently I have noticed that the service is no longer working (HTTP Error 503. The service is unavailable):
http://codeconverter.sharpdevelop.net/ConvertService.asmx/

Could you please, provide some more information if the service will be available again soon?

**Comment by christophwille** [comment]
Sorry we don't have uptime monitoring on that site, so it being down went unnoticed (definitely not intended). It is now back up and running.

**Comment by APopatanasov** [comment]
Great news! Thanks a lot for fixing it so fast. 😊 😊

**Comment by christophwille** [comment]
If you need a more modern version please check out

https://roslyncodeconverter.azurewebsites.net/

C# to VB and vice versa is supported via Roslyn.
