### ISSUE TITLE
CodeConverter service again not available

### ISSUE THREAD

**Issue by APopatanasov** [icsharpcode/NRefactory#526]
Hi guys, 
It seems the service is down again with error (HTTP Error 503. The service is unavailable) 😢 as it was the case with [this ](https://github.com/icsharpcode/NRefactory/issues/524)issue. 
Could you please, check it again and let me know when it will be available?

Thanks in advance. 😄

**Comment by christophwille** [comment]
back up; the app pool seems to be running into the limits of rapid fail protection (which given we haven't changed a thing in years is kind of weird)

**Comment by APopatanasov** [comment]
Thanks, again! 🥇

**Comment by APopatanasov** [comment]
Hi @christophwille ,
I really apologize for bothering you again for this, but the service is down again. Could you please, check it? I have also decided to migrate to the other [converter ](https://roslyncodeconverter.azurewebsites.net/)suggested by you. I hope after migrating to it such problems with the service won't be observed.

Thanks again in advance. 😄

**Comment by christophwille** [comment]
The old code converter is now offline for good and very, very likely won't come back.

**Comment by APopatanasov** [comment]
😄 @christophwille  thanks for the information.

**Comment by APopatanasov** [comment]
Hi @christophwille I apologize for bothering you again, but I have one additional question. Could you please provide me information about the license [the new converter](https://roslyncodeconverter.azurewebsites.net/) is under? I was not able to find it.

Thanks.

**Comment by christophwille** [comment]
https://github.com/icsharpcode/RefactoringEssentials/blob/master/LICENSE.txt

**Comment by APopatanasov** [comment]
Thanks again. 🥇

**Comment by christophwille** [comment]
And yes, we do take pull requests in the RE repo because the "new" converter in RE is not as sophisticated yet as the old one was (esp VB->C#).

**Comment by APopatanasov** [comment]
Thanks for the info. I need the C#->VB conversion, but it is a valuable information and I will have it in mind if I start using it for VB->C# conversion.

**Comment by APopatanasov** [comment]
@christophwille I have an additional question. I have checked the[ clients repository](https://github.com/christophwille/roslyncodeconverterclients) of the converter. For WPF is seems to be working, however is there a way to make a client for Silverlight as well - has the REST API support for Silverligh?
Thanks.

**Comment by christophwille** [comment]
The REST API itself has no client restrictions whatsoever (Python, JS, you name it is just fine). But I think AutoRest might generate code that is not taking SL into account.

**Comment by APopatanasov** [comment]
@christophwille Silverlight I believe is allowed to connect to servers that have a cross domain policy files (clientaccesspolicy.xml) otherwise the connection is denied for security reason. I have tried to make a client of my own for SL using the WebClient, but an error was telling me that the connection could not be established due to the missing above file. If there is no way to connect to the service for Silverlight is there some offline version of the previous converter that I could use and integrate into my project.

I apologize for bothering you with so many questions, but the conversion functionality is very important for my application - it is a WPF and SL app.

**Comment by APopatanasov** [comment]
Also I need to target .NET Framework 4.0.

**Comment by christophwille** [comment]
Please open a new issue on the RE repo, as this is getting longer and also no longer related to NR.
