### ISSUE TITLE
How to implement NRefactory

### ISSUE THREAD

**Issue by vietson** [icsharpcode/NRefactory#535]
Hello ! I'm newbie of ICSharpCode.NRefactory
I want parse source code file (*.cs) and extract information (ex : namespace, classname, mothed, statement,..)
So, how to implement NRefactory ?
Thanks

**Comment by lextm** [comment]
Read carefully the first few paragraphs and then check out Roslyn,

https://github.com/icsharpcode/NRefactory/blob/master/README

**Comment by vietson** [comment]
@lextm thank for your answer. I understand !
